//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCF.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class BehaviorUser
    {
        public string userName { get; set; }
        public string behavior { get; set; }
        public string atTimeInHandling { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
