//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCF.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptInfo
    {
        public int id { get; set; }
        public int idReceipt { get; set; }
        public int idProduct { get; set; }
        public Nullable<int> count { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Receipt Receipt { get; set; }
    }
}
